### ISSUE TITLE
Get All Event Endpoint

### ISSUE THREAD

**Issue by FongChanatip** [CSE110-FA24-14/Sync-De-Stress#50]
**As a:** Dev

**I want:** to be able to retrieve all events from the database

**So that:** I can display events to the user

**Can be split:**

**Blocked by:**

**Split from:**

### Acceptance Criteria
- [ ] In backend
- [ ] Auth required
- [ ] GET `/events?sort={}&max={}`
- [ ] sort by `asc`, `dsc`
- [ ] works with and without params

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the events route and controller to retrieve all events from the database with optional sorting and pagination. Added authentication requirement and implemented the specified query parameters.

You can review changes in this commit: https://github.com/lattaai13/CSE110-FA24-14-Sync-De-Stress-50/commit/fcd8094598d25301e2be1e48e633c44761d0ba48.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
